# Generated by Django 4.1.2 on 2022-10-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=12)),
                ('whatsapp_no', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=25)),
                ('Date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('college_state', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=40)),
                ('passing_year', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Apply_status', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Apply_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('Apply_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboarduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=10)),
                ('cnf_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('code_type', models.CharField(max_length=100)),
                ('valid_date', models.DateField()),
            ],
        ),
    ]
