# Generated by Django 4.1.2 on 2022-11-20 12:54

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=backend.models.Account.nowdate),
        ),
    ]
