# Generated by Django 4.1.2 on 2022-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
