# Generated by Django 4.1.2 on 2022-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_account_enrolment_account_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_state',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='opening',
            name='job_type',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
