# Generated by Django 4.1.2 on 2022-12-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_account_employee_status_account_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
