# Generated by Django 4.1.2 on 2022-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_opening_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
