# Generated by Django 4.1.2 on 2022-12-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_opening_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='description',
            field=models.CharField(max_length=30000),
        ),
    ]
